<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class HumcareForm extends Model
{
    use HasFactory;

    // protected $fillable = [
    //     'firstName',
    //     'lastName' ,
    //     'address',
    //     'postCode',
    //     'telephoneNo',
    //     'insuranceName',
    //     'dayTimeTelephone',
    //     'mobileTelephone',
    //     'dob',
    //     'email',
    //     'takeEmployment',
    //     'cleanLicense', 
    //     'employeerName',
    //     'employeerAddress',
    //     'employeerPostCode', 
    //     'employeerTitle', 
    //     'employeerDOA',
    //     'salary',
    //     'dept', 
    //     'dutiesDescription',
    //     'periodOfNotice',
    //     'lastDayService', 
    //     'reason4Leaving',
    //     'nameOfEmployeer2',
    //     'employeerAddress2',
    //     'employeerPostCode2',
    //     'employeerPostHeld2',
    //     'duties2',
    //     'reason4leaving2',
    //     'dutiesSummary2',
    //     'university',
    //     'course',
    //     'qualification',
    //     'profQualification',
    //     'courseDetails',
    //     'membership',
    //     'trainingProgram',
    //     'courseDuration',
    //     'personalStatement',
    //     'conviction',
    //     'convictionDetails',
    //     'underTaking',
    //     'disability',
    //     'offence',
    //     'sicknessAbsence', 
    //     'refereeName1',
    //     'refereePosition1', 
    //     'refereeRelationship1',
    //     'refereeOrganization1',
    //     'refereeAddress1',
    //     'refereePostCode1' ,
    //     'refereeTelephone1',
    //     'refereeEmail1', 
    //     'refereeName2', 
    //     'refereePosition2',
    //     'refereeRelationShip2',
    //     'refereeOrganization2',
    //     'refereeAddress2', 
    //     'refereePostCode2', 
    //     'refereeTelephone2',
    //     'refereeEmail2',
    //     'approachReferee',
    //     'bankName',
    //     'bankBranch',
    //     'nameOnCard',
    //     'accountNumber',
    //     'sortCode',
    //     'postApplication',
    //     'ethnicGroup',
    //     'gender',
    //     'diabilityConfirm',
    //     'presentStatus',
    //     'age',
    //     'passportBirth',
    //     'proofOfWork',
    //     'proofOfAddress',
    //     'originalCertificate',
    //     'certificateTraining',
    //     'passportPhoto',
    //     'bankSocietyDetails',
    //     'dbsCertificate',
    //     'nationalInsurance',
    //     'curriculumVitae',
    // ];

    protected $guarded = [];
}
